export const defaultSysConfig = {
  websiteName: '极简论坛',
  websiteUrl: '',
  webBgimage: '',
  websiteKeywords: '极简,论坛,极简论坛',
  websiteDescription: '极简论坛',
  favicon: '',
  pointPerPost: 5,
  pointPerPostByDay: 20,
  pointPerComment: 1,
  pointPerCommentByDay: 20,
  pointPerLikeOrDislike: 1,
  pointPerDaySignInMin: 1,
  pointPerDaySignInMax: 10,
  websiteAnnouncement: '',
  css: '',
  js: '',
  postUrlFormat: {
    type: 'UUID',
    minNumber: 10000,
    dateFormat: 'YYYYMMDDHHmmssSSS',
  },
  invite: false,
  createInviteCodePoint: 100,
  regWithEmailCodeVerify: false,
  email: {
    apiKey: '',
    from: '',
    senderName: '',
    to: '',
  },
  turnstile: {
    siteKey: '',
    secretKey: '',
    enable: false,
  },
  notify: {
    tgBotEnabled: false,
    tgBotToken: '',
    tgBotName: '',
    tgSecret: '',
  },
  upload: {
    imgStrategy: 'r2',
    attachmentStrategy: 'r2',
  },
}
