PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uid TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  last_login TEXT,
  email TEXT NOT NULL UNIQUE,
  avatar_url TEXT NOT NULL,
  head_img TEXT,
  point INTEGER NOT NULL DEFAULT 0,
  post_count INTEGER NOT NULL DEFAULT 0,
  comment_count INTEGER NOT NULL DEFAULT 0,
  role TEXT NOT NULL DEFAULT 'USER',
  level INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'NORMAL',
  banned_end TEXT,
  css TEXT,
  js TEXT,
  signature TEXT,
  last_active TEXT,
  invited_by_id INTEGER,
  tg_chat_id TEXT,
  secret_key TEXT,
  FOREIGN KEY (invited_by_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS titles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL UNIQUE,
  count INTEGER NOT NULL DEFAULT 0,
  style TEXT NOT NULL,
  status INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS user_titles (
  user_id INTEGER NOT NULL,
  title_id INTEGER NOT NULL,
  PRIMARY KEY (user_id, title_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (title_id) REFERENCES titles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  en_name TEXT UNIQUE,
  "desc" TEXT NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  hot INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pid TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  uid TEXT NOT NULL,
  view_count INTEGER NOT NULL DEFAULT 0,
  reply_count INTEGER NOT NULL DEFAULT 0,
  like_count INTEGER NOT NULL DEFAULT 0,
  dis_like_count INTEGER NOT NULL DEFAULT 0,
  min_level INTEGER NOT NULL DEFAULT 1,
  tag_id INTEGER NOT NULL,
  read_role INTEGER NOT NULL DEFAULT 0,
  pinned INTEGER NOT NULL DEFAULT 0,
  point REAL NOT NULL DEFAULT 0,
  last_comment_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_comment_uid TEXT,
  hide INTEGER NOT NULL DEFAULT 0,
  hide_content TEXT,
  pay_point INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES tags(id),
  FOREIGN KEY (last_comment_uid) REFERENCES users(uid)
);

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cid TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  uid TEXT NOT NULL,
  pid TEXT NOT NULL,
  mentioned TEXT NOT NULL DEFAULT '[]',
  content TEXT NOT NULL,
  floor INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE,
  FOREIGN KEY (pid) REFERENCES posts(pid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS favorites (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  pid TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (pid) REFERENCES posts(pid) ON DELETE CASCADE,
  UNIQUE (user_id, pid)
);

CREATE TABLE IF NOT EXISTS comment_likes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  pid TEXT NOT NULL,
  cid TEXT NOT NULL,
  uid TEXT NOT NULL,
  FOREIGN KEY (pid) REFERENCES posts(pid) ON DELETE CASCADE,
  FOREIGN KEY (cid) REFERENCES comments(cid) ON DELETE CASCADE,
  FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE,
  UNIQUE (uid, cid)
);

CREATE TABLE IF NOT EXISTS comment_dislikes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  pid TEXT NOT NULL,
  cid TEXT NOT NULL,
  uid TEXT NOT NULL,
  FOREIGN KEY (pid) REFERENCES posts(pid) ON DELETE CASCADE,
  FOREIGN KEY (cid) REFERENCES comments(cid) ON DELETE CASCADE,
  FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE,
  UNIQUE (uid, cid)
);

CREATE TABLE IF NOT EXISTS post_support (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uid TEXT NOT NULL,
  pid TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE,
  FOREIGN KEY (pid) REFERENCES posts(pid) ON DELETE CASCADE,
  UNIQUE (uid, pid)
);

CREATE TABLE IF NOT EXISTS sys_config (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS point_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reason TEXT NOT NULL,
  uid TEXT NOT NULL,
  pid TEXT,
  cid TEXT,
  point INTEGER NOT NULL,
  remark TEXT,
  FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE,
  FOREIGN KEY (pid) REFERENCES posts(pid) ON DELETE CASCADE,
  FOREIGN KEY (cid) REFERENCES comments(cid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  read INTEGER NOT NULL DEFAULT 0,
  from_uid TEXT,
  to_uid TEXT NOT NULL,
  content TEXT NOT NULL,
  type TEXT,
  relation_id TEXT,
  FOREIGN KEY (from_uid) REFERENCES users(uid) ON DELETE SET NULL,
  FOREIGN KEY (to_uid) REFERENCES users(uid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS invite_codes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  from_uid TEXT NOT NULL,
  to_uid TEXT,
  content TEXT NOT NULL UNIQUE,
  FOREIGN KEY (from_uid) REFERENCES users(uid) ON DELETE CASCADE,
  FOREIGN KEY (to_uid) REFERENCES users(uid) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS email_codes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  key TEXT NOT NULL UNIQUE,
  code TEXT NOT NULL,
  valid_at TEXT NOT NULL,
  used INTEGER NOT NULL DEFAULT 0,
  reason TEXT NOT NULL,
  target_email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  pid TEXT NOT NULL,
  uid TEXT NOT NULL,
  point INTEGER NOT NULL,
  FOREIGN KEY (pid) REFERENCES posts(pid) ON DELETE CASCADE,
  FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE,
  UNIQUE (pid, uid)
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_uid ON users(uid);
CREATE INDEX IF NOT EXISTS idx_posts_uid ON posts(uid);
CREATE INDEX IF NOT EXISTS idx_posts_tag_id ON posts(tag_id);
CREATE INDEX IF NOT EXISTS idx_posts_point ON posts(point DESC);
CREATE INDEX IF NOT EXISTS idx_comments_pid ON comments(pid);
CREATE INDEX IF NOT EXISTS idx_comments_uid ON comments(uid);
CREATE INDEX IF NOT EXISTS idx_favorites_user_id ON favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_point_history_uid ON point_history(uid);
CREATE INDEX IF NOT EXISTS idx_messages_to_uid ON messages(to_uid);
CREATE INDEX IF NOT EXISTS idx_invite_codes_from_uid ON invite_codes(from_uid);
